### ISSUE TITLE
CNN_LSTM Not included in the codebase

### ISSUE THREAD

**Issue by chenhh17** [BehnamZeinali/IMUNet#5]
I notice that the CNN_LSTM module in the main.py file at RONIN_torch is not imported correctly, and there is no such file at the codebase. Is this code file missing? I am performing further research based on your code.

**Comment by BehnamZeinali** [comment]
Hello, At first, I designed the CNN_LSTM model for this purpose. After testing, though, the CNNs' performance was better than that of my designed model, so I put that path aside.

**Comment by chenhh17** [comment]
Thanks for letting me know that!
